from pathlib import Path
r=Path(__file__).resolve().parents[1];s=r/'specifications/p2rank-binding-pockets';mrs=(s/'mrs.md').read_text()
import re
ids=sorted(set(re.findall(r'MRS-(?:[A-Z]+-)?\d{3}',mrs)))
sections={
'Document Control':'''| Field | Value |
| --- | --- |
| MTS identifier | P2R-MTS-001 |
| Version | 1.0 |
| Status | In review |
| Last revised | 2026-10-04 |
| MRS | P2R-MRS-001 version1.0 Approved by user's exact-brief implementation request |
| Biosimulant fit | Adapter fit |

Revision History:1.0,2026-10-04, frozen predictor/preprocessing/metric design; release gates remain unevaluated. The skill start_mts copier failed its protected-template integrity check (observed c708b858df53dd404f0d22a444d619e3590a9a03e21b98b54da3c80a4a07a4dc). This independently authored MTS follows the required sections; no protected skill file was changed.''',
'Technical Decision Summary':'MTS-001: Freeze P2Rank2.5.1 native Java inference behind a finite typed adapter. Reversible canonical PDB conversion avoids ambiguous upstream author IDs. Retain exact assets before publishable inference. An asset-retention revision is private infrastructure only, never the published scientific Lab.',
'Scope, Boundaries, and Assumptions':'All exact MRS gates apply. Small X-ray structures; no training. First model; occupancy-resolved alternates; protein heavy atoms only. Default model/B-factor feature stays unchanged. Require PDB/mmCIF upload, selected author chains and top_n1–10. Report limitations for non-X-ray structures.',
'MRS Traceability':'\n'.join(f'| {x} | Predictor/structure/retention implementation | Frozen tests, managed byte verification and gate matrix | Agent evidence custodian |'for x in ids)+'\n\nA1–A5/H1–H8 map individually to reports/acceptance.md and retain original exact criteria from MRS. No grouped mapping waives any gate.',
'Architecture and Data Flow':'Upload→Gemmi parser→first-model/chain/altloc/protein-only canonical PDB + reversible map→pinned Java predictor→strict CSV parser→ranked pockets/residue assignments/surface points→typed report + artifacts +3D views. Separate held-out ligand coordinates enter evaluation only, never predictor.',
'Data Implementation':'Three fixtures1CRN,1STP,7L13 from RCSB CC0. Freeze exact bytes/mapping/processed proteins/reference ligand before final evaluation. 7L13 released2021; upstream default-model documentation says Chen11 training. Confirm eligibility with retained training/source evidence. Transform an additional mapping fixture with multi-character label/author chains, overlapping numbers, gaps and insertion codes; it is software verification only.',
'Input, Output, and Error Contracts':'Input structure_file formatpdb plus optional mmcif_file formatcif (exactly one), chains_json unique author IDs, top_ninteger1–10. Input content bounded2MiB,10000heavy atoms/2000residues/62chains. Invalid input returns statusinvalid_input/code/message and no prediction. Predictor timeout returns timeout; upstream failures return execution_failed; valid empty CSV returns no_pockets. Raw outputs preserved. Mixed report record gives centers/surface xyz Å, dimensionless upstream scores/probability, exact original residue keys and internal viewer keys; count output count. Artifact paths are typed files, retained by managed execution.',
'Model Method and Uncertainty':'Unmodified pinned P2Rank default random forest and config, seed42,threads1. Execute launcher with supported Java21; explicit JVM maxheap2048MiB. No recalibration/resorting. Score/probability preserved within emittedprecision, centers1e-3Å tolerance. Calibrated upstream probability remains a model estimate. Frozen held-out metric is closest center-to-ligand-heavy-atom distance<=4Å, top1/top3; no outcome tuning.',
'Biosimulant Fit Assessment':'Adapter fit: preserve authoritative native Java predictor while adding upload validation, typed ports, immutable assets, reproducible results and retained views. Native model training is excluded.',
'Biosimulant Realization':'Subclass biosim.BioModule; import ExecutionPolicy from biosim; execute(inputs, *, context) withExecutionPolicy.ONCE_BEFORE_RUN. model.yaml declaresonce_before_run and exactports. No timing/settle-dependent inference. visualize() reads computed state only. Declare requiredstructure3dandtext (invalid input givestext explanation;3D unavailable is explicit). Native3D loads processedstructure, while retainedoffline HTML3Dmol2.5.5 shows coloredcenters/pointcloud surface/residues and original identity labels. Reopening/selected-residue behavior requires actual browserverification.',
'Verification and Test Design':'Independent standalone original2.5.1 distribution commands on three frozen processedinputs, then separateadapter invocation. Compare all orderedpockets, rawresidue rows, mappedidentities, score precision and1e-3Å centers. Verify insertion/gaps/chains via roundtrip mapping and actual highlightedatom selectors. Freeze4Å and referenceXF7/chainA/401 from7L13 separately; report nearest-distance and top1/top3 recovery. Empty/nonprotein/format/top_n/chain/bounds/timeout/upstreamfailure unit tests plus composedCLI and managed typedoutputs/assets verification. No-pocket fixture1CRN is actual native emptyoutput. Execute actualstudy top1/top3 on same7L13example, deliberatepublic runs and visibleResults/Experiments.',
'Reproducibility, Security, Performance, and Cost':'Python3.12, biosimulant==0.0.34,gemmi==0.7.3,jdk4py==21.0.8.1. Java21.0.8 wheel hashes for Linuxamd64/arm64 retained. Sourcecommit9808a7723be9a94e2ffc21ab5f724cb6ae4ba01e; distroSHA d243f2d9036ac053fefb9407b5fe1c85f4fe077c519fd975ac585e995feab274; defaultmodelSHA9c3fc8becd5e5db4a7d7a9026e19f68b0f85fd4723056d71be8fcc7cd2774962. Runtime archives extract into unique invocation directory with strictzip traversal/size checks. Baselineinference isoffline: missingassetfail, no networkfetch. Asset-retentionrun downloads exactknownURLs with pinnedchecksums solelybefore finalinference. No signedURLs in code/examples. Each invocation uses ownmode700temp directory; cannotread otherusersfiles through publicpaths. Subprocess timeout≤remaining300s and kills processgroup. ModalCPU2cores/4096MiBpilot; finalprofile selectedfromlivecatalog. Price/spendonlymeasured/preflight, nofabricatedinvoice.',
'Model Lock, Release, and Operations':'MTS-002: Freeze code, runtime archives, fixtures, source licenses and acceptance protocol before final validation. Required3structurepilot≤300s each; measure largerboundbeforeadvertising. Stagingonlycommits/push; no coreproductiondeployment. Publicplan digest and hostingexactrelease require approval. Hostingmax1container,minwarm0/scalezero, exact300s timeout and realuploadboundsmustpasspreflight. Publish/Hublisting/managedrun/hostedrun/publicstudyareseparateevidence. Disablewithhosting_update pause orwithdraw usingcurrentrevision; preserveexistingModalproduction.',
'Risks, Decisions, and Open Questions':'Release blockersownedbyagent/platform:113distributedJAR rightsandcorrespondingsources audit, nativeoverlaylack, genericproteinfilehostingcapability, actualpublicstudy exposure and matchingHTMLartifactmetadata. Item remains incomplete until resolved. Runtime licensing is not inferred from top-levelMIT. Public release must notclaim fullqualification merely becauseexecutionpassed.',
'References and Glossary':'MRS P2R-MRS-001version1.0; exactitem03brief; upstream2.5.1README/config/modelsreadme; RCSB policiesCC0; live Biosimulant scientific-authoring-14contract. Runtime JSON and immutable files are evidence, stdoutdiagnosticsonly.',
'Predictive / ML Technical Module':'No fittedparameters change. Existing defaultmodel and scoretransformers authoritative. Preserve all adjacentresidue assignments, surfacepoints and scalar precision. Per-structuretimingmemorymeasuredwithreceipt; smallheldoutrecoverydemonstrationdoesnotestablishpopulationaccuracy.'}
(s/'mts.md').write_text('# P2Rank Binding Pockets — Modeling Technical Specification\n\n'+'\n\n'.join(f'## {i}. {k}\n\n{v}'for i,(k,v)in enumerate(sections.items(),1))+'\n')
