from pathlib import Path
import sys,yaml
r=Path(__file__).resolve().parents[1];lab=r/'labs/binding-pockets'
sys.path.insert(0,str(lab/'models/predict'));from src.predictor import FILES
inputs=[{'name':'structure_file','signal_type':'scalar','dtype':'str','value_type':'file','format':'pdb','required':False,'description':'Upload protein PDB (<=2MiB); provide exactly one PDB or mmCIF file.'},
{'name':'mmcif_file','signal_type':'scalar','dtype':'str','value_type':'file','format':'cif','required':False,'description':'Upload text mmCIF (<=2MiB); preserve author/label chain and residue mappings.'},
{'name':'chains_json','signal_type':'scalar','dtype':'str','value_type':'string','default':'[]','required':False,'max_length':1024,'description':'Selected author chain IDs as JSON list; [] selects all protein chains in first model.'},
{'name':'top_n','signal_type':'scalar','dtype':'int64','value_type':'integer','default':3,'required':False,'description':'Top1–10ranked pockets.'}]
outputs=[{'name':'report','signal_type':'record','schema':{'status':'str','pockets':'json','residues':'json','surface_points':'json','receipt':'json'},'emitted_unit':'1'},
{'name':'pocket_count','signal_type':'scalar','dtype':'int64','emitted_unit':'count'},
*({'name':k,'signal_type':'scalar','dtype':'str','value_type':'file','format':v}for k,v in FILES.items())]
deps=['biosimulant==0.0.34','gemmi==0.7.3','jdk4py==21.0.8.1']
model={'schema_version':'2.0','package':'p2rank-pocket-predictor','version':'0.1.0','title':'P2Rank Pocket Predictor','description':'Offline finite2.5.1coordinate-to-pocket adapter with reversible residue mapping.','standard':'other','license':'MIT','biosim':{'entrypoint':'src.predictor:PocketPredictor','execution_policy':'once_before_run','communication_step':1.0},'io':{'inputs':inputs,'outputs':outputs},'runtime':{'python_version':'3.12','dependencies':{'packages':deps}}}
(lab/'models/predict/model.yaml').write_text(yaml.safe_dump(model,sort_keys=False))
manifest={'schema_version':'2.0','package':'p2rank-binding-pockets','version':'0.1.0','title':'P2Rank Binding-Pocket Prediction','description':'Upload a protein PDB or mmCIF and inspect ranked candidate pockets, original residue assignments, Å centers and surface points. Download a reopenable offline3D pocket result. Research estimates, not confirmed binding sites.','license':'MIT','models':[{'alias':'predict','path':'models/predict'}],'wiring':[],
'io':{'inputs':[{**p,'maps_to':'predict.'+p['name']}for p in inputs],'outputs':[{**p,'maps_to':'predict.'+p['name']}for p in outputs]},'runtime':{'python_version':'3.12','duration':1.0,'communication_step':1.0,'initial_inputs':{'predict.mmcif_file':'fixtures/7L13.cif','predict.chains_json':'[]','predict.top_n':3},'dependencies':{'packages':deps}},
'hardware':{'compute':{'device':'cpu','cpu_cores':2,'memory_mb':4096,'recommended_profile':'pro'}},'intended_use':{'statement':'Research candidate binding-pocket localization from small protein coordinate structures; no experimental binding or clinical claim.'},'caveats':['Default pretrainedP2Rank2.5.1; B-factors contribute to model features.','Protein-only first model and occupancy-resolved alternate coordinates; waters/ligands removed.','Original author/label IDs and insertion codes preserved in downloadable map.','Scores/probabilities are upstream model estimates.','Three-structure parity and one held-out4Å demonstration do not establish broad accuracy.','Native3Dpreview shows protein; downloadable offlinepocket-view.html contains computed colored pocket centers, pointcloud surface and residue highlights.','Runtime includes upstreamGPL/LGPL dependencies; consult full notices/source obligations before redistribution.'],'prohibited_claims':['Experimentally confirmed binding site','Binding affinity','Clinical utility','Broad biological validation'],
'visualization':{'schema_version':'1','required':[{'module':'predict','render':'structure3d','min_count':1},{'module':'predict','render':'text','min_count':1}]}}
(lab/'lab.yaml').write_text(yaml.safe_dump(manifest,sort_keys=False))
