from pathlib import Path
r=Path(__file__).resolve().parents[1];s=r/'specifications/p2rank-binding-pockets';brief=(r.parents[1]/'outputs/hub-hosting-briefs-2026-10-03/03-p2rank-binding-pockets.md').read_text()
accept=brief.split('### Item-specific acceptance criteria')[1].split('## Completion record')[0]
sections={
'Document Control':'''| Field | Value |
| --- | --- |
| MRS identifier | P2R-MRS-001 |
| Version | 1.0 |
| Status | Approved |
| Last revised | 2026-10-04 |
| Selected type or types | Predictive / ML |

Approval receipt: user's 2026-10-04 goal explicitly authorizes implementing the complete item03 brief and its unchanged acceptance criteria. Approval covers requirements and staging implementation, not a compute grant, public plan digest or production deployment. Agent is implementation/evidence custodian; user owns intended use and release decisions.

Revision History: 1.0, 2026-10-04: exact brief transcribed with explicit preprocessing and verification procedures; no acceptance threshold weakened.''',
'Executive Summary':'Rank candidate binding pockets from uploaded protein coordinates with frozen P2Rank. The goal is a hosted, public, downloadable research Lab; every gate must pass before DONE.',
'Biological Objective and Intended Use':'One finite prediction per invocation. Support exploratory localization of candidate ligand-binding pockets. Scores and probabilities are upstream model estimates, not experimental binding evidence. No affinity, safety, clinical, or universal accuracy claims. Sequence-only inputs are insufficient.',
'Model Definition and Scope':'CPU Java P2Rank 2.5.1 default pretrained model; no training, model tuning, implicit structure prediction or external inference service. Initial pilot is three small reference structures, maximum300seconds per invocation. Provisional protective input limits:2MiB,10000protein heavy atoms,2000residues,62chains; measured support remains a gate, not a claim.',
'Inputs':'''MRS-IN-001: Upload one UTF-8 .pdb/.cif/.mmcif atomic-coordinate structure and select author chains (empty selection means all); top_n integer1–10. Reject empty/nonprotein, unsupported extensions, malformed coordinates, missing selected chains or bounds violations explicitly. Binary CIF and compressed uploads are outside this release.

MRS-IN-002: Select first coordinate model; remove waters, ligands, hydrogen atoms and non-amino-acid entities; choose highest occupancy alternate per atom (ties prefer blank then A then lexical). Preserve author/label chain IDs, author residue number, insertion code and label sequence ID through a downloadable reversible mapping. Separate chains with equal author numbers must never collide.''',
'Outputs':'''MRS-OUT-001: Return ordered pocket rank, unchanged upstream score and probability if present, x/y/z centers in Å, surface points and exact original residue identities. Retain raw prediction/residue CSVs, processed structure, mapped residues/pockets JSON/CSV, receipt and source identities. Empty pocket list is a successful no_pockets result, never an invented site.

MRS-OUT-002: Show a reusable interactive3D protein view and a reopenable offline pocket view with colored centers/surface points and individually selectable residue highlights, using the computed outputs. Include author identity labels and Å units. Native platform3D may be a protein preview; overlay support must be verified separately. Exact ranks/scores accompany3D; no ad hoc chat visual substitutes.''',
'Data, Assay, and Evidence Specification':'MRS-DQ-001: Retain three legally usable RCSB/upstream structures and their independently verified bytes/licenses. Preserve any reference ligand separately and remove it before inference. Choose a post-training held-out holo structure before reading outcomes. Freeze source/model/runtime/fixtures,4Å metric and no tuning protocol before final verification. Software mapping fixtures may transform coordinates/IDs with documented provenance; these are not biological accuracy cases.',
'Ground Truth or Estimand':'Closest Euclidean distance from each predicted center to any retained reference-ligand heavy atom; recovery if minimum distance<=4Å. top1 and top3 use first1/3 ranked centers, respectively. Reference ligand is absent from predictor input. This is a small demonstration, not a broad accuracy estimate.',
'Generalization Domain':'Uploaded small protein-coordinate structures within measured limits. X-ray default uses B-factors; non-X-ray/AlphaFold confidence conventions limit interpretation. No accuracy claims for all proteins, membranes, ensembles or biological function.',
'Performance Requirements':'MRS-OPS-001: Pilot three small structures on approved CPU Java runtime, each invocation<=300seconds. Record cold/warm latency, available peak memory and provider spend; cap concurrency and scale idle resources to zero. No unbounded jobs. Separate local adapter tests, managed runs, end-to-end staging and hosting evidence.',
'Validation Plan':'MRS-001: Execute all exact A1–A5 and H1–H8 gates below unchanged. Parity uses separate pinned standalone commands, centers tolerance1e-3Å and scores within emitted precision. No reference-result literals may self-certify acceptance. Managed/hosted result bytes must independently match immutable size/SHA-256. Model/fixtures/protocol lock precedes evaluation.',
'Acceptance and Traceability':accept,
'Constraints, Risks, and Governance':'MRS-002: Development/tests/commits/push on staging only, synchronized from main preserving staging-only work. Dedicated repository. Production stays Modal. Concrete staging review and fresh explicit user permission required before production deployment. Obtain item-specific bounded managed-compute approval and exact public/hosting approval. License/rights gaps are blockers.',
'Reproducibility, Deliverables, and Handoff':'MRS-003: Retain exact code, model/config/runtime/digests/licenses, immutable workspace/release, matching Passport, public URL/results/study/downloads, input/cost/latency limits and disable instructions. Record every gate; brief/index DONE only after all pass. Never retain signed URLs or private uploads in deliberate public examples.',
'Milestones and Responsibilities':'Agent: discovery, assets, code/tests, frozen evidence, concrete approval plans, byte verification and gate records. User: bounded compute/public/production approvals. Platform: exact release hosting and public study/result capabilities. No deployment assumed.',
'Open Questions and Decisions':'Public generic protein-upload hosting,3D overlays, public studies and artifact-metadata integrity are unverified platform capabilities. Java and shipped third-party license closure are required. These are release gates with agent/platform owners; no acceptance waiver.',
'References and Glossary':'Source brief item03; https://github.com/rdk/p2rank/tree/2.5.1 ; https://www.rcsb.org/pages/policies ; live Biosimulant authoring contract scientific-authoring-14/runtime0.0.34. Å=angstrom; author IDs identify deposited residues; internal IDs are reversible predictor identifiers.',
'Predictive / ML Module':'Frozen existing pretrained predictor, no training/calibration/feature selection. Verify parity to native output and report held-out holo distances under frozen4Å definition. Upstream probability is a model estimate, not certainty. Hold-out eligibility requires exclusion from frozen training sources; otherwise A3 remains blocked.'}
(s/'mrs.md').write_text('# P2Rank Binding Pockets — Model Requirements Specification\n\n'+'\n\n'.join(f'## {i}. {k}\n\n{v}' for i,(k,v) in enumerate(sections.items(),1))+'\n')
