from pathlib import Path
import sys,yaml
r=Path(__file__).resolve().parents[1];lab=r/'labs/binding-pockets'
sys.path.insert(0,str(lab/'models/predict'));from src.predictor import FILES
inputs=[{'name':'structure_file','signal_type':'scalar','dtype':'str','value_type':'file','format':'pdb','required':False,'description':'Upload protein PDB (<=2MiB); provide exactly one PDB or mmCIF file.'},
{'name':'mmcif_file','signal_type':'scalar','dtype':'str','value_type':'file','format':'cif','required':False,'description':'Upload text mmCIF (<=2MiB); preserve author/label chain and residue mappings.'},
{'name':'chains_json','signal_type':'scalar','dtype':'str','value_type':'string','default':'[]','required':False,'max_length':1024,'description':'Selected author chain IDs as JSON list; [] selects all protein chains in first model.'},
{'name':'top_n','signal_type':'scalar','dtype':'int64','value_type':'integer','default':3,'required':False,'description':'Number of top-ranked pockets to return (1–10).'}]
outputs=[{'name':'report','signal_type':'record','schema':{'status':'str','pockets':'json','residues':'json','surface_points':'json','receipt':'json'},'emitted_unit':'1'},
{'name':'pocket_count','signal_type':'scalar','dtype':'int64','emitted_unit':'count'},
*({'name':k,'signal_type':'scalar','dtype':'str','value_type':'file','format':v}for k,v in FILES.items())]
deps=['biosimulant==0.0.34','gemmi==0.7.3','jdk4py==21.0.8.1']
model={'schema_version':'2.0','package':'p2rank-pocket-predictor','version':'0.1.0','title':'P2Rank Pocket Predictor','description':'Finite offline adapter around pinned P2Rank 2.5.1 with reversible residue mapping.','standard':'other','license':'MIT','biosim':{'entrypoint':'src.predictor:PocketPredictor','execution_policy':'once_before_run','communication_step':1.0},'io':{'inputs':inputs,'outputs':outputs},'runtime':{'python_version':'3.12','dependencies':{'packages':deps}}}
(lab/'models/predict/model.yaml').write_text(yaml.safe_dump(model,sort_keys=False))
manifest={'schema_version':'2.0','package':'p2rank-binding-pockets','version':'0.1.0','title':'P2Rank Binding-Pocket Prediction','description':'Upload a protein structure (PDB or mmCIF) and get ranked candidate ligand-binding pockets from P2Rank 2.5.1: scores, centers and surface points in Å, residue assignments with original chain and residue IDs, and a downloadable interactive 3D pocket view. Model estimates, not experimentally confirmed binding sites.','license':'MIT','models':[{'alias':'predict','path':'models/predict'}],'wiring':[],
'io':{'inputs':[{**p,'maps_to':'predict.'+p['name']}for p in inputs],'outputs':[{**p,'maps_to':'predict.'+p['name']}for p in outputs]},'runtime':{'python_version':'3.12','duration':1.0,'communication_step':1.0,'initial_inputs':{'predict.mmcif_file':'fixtures/7L13.cif','predict.chains_json':'[]','predict.top_n':3},'dependencies':{'packages':deps}},
'hardware':{'compute':{'device':'cpu','cpu_cores':2,'memory_mb':4096,'recommended_profile':'pro'}},'intended_use':{'statement':'Research candidate binding-pocket localization from small protein coordinate structures; no experimental binding or clinical claim.'},'caveats':['Default pretrained P2Rank 2.5.1 model (trained on CHEN11); B-factors contribute to its features, so predicted or non-X-ray structures need extra care.','Uses protein heavy atoms from the first model only; alternate locations resolved by highest occupancy; waters, ligands and other non-amino-acid residues removed.','Original author and label chain/residue IDs, including insertion codes, are preserved in the downloadable residue map and labels.','Scores and probabilities are upstream model estimates, not binding evidence.','Exact parity on three reference structures and one held-out 4 Å demonstration (7L13) do not establish broad accuracy.','The native 3D panel previews the processed protein; the downloadable pocket-view.html shows colored pocket centers, surface points and residue highlights offline.','The runtime bundles unmodified GPL/LGPL Java components (e.g. Weka, FastRandomForest, CDK, BioJava); notices are in assets/license-records.zip and exact corresponding source in assets/corresponding-sources.zip. vecmath-1.3.1 and openchart-1.4.2 are omitted from the upstream distribution (outputs verified identical).'],'prohibited_claims':['Experimentally confirmed binding site','Binding affinity','Clinical utility','Broad biological validation'],
'visualization':{'schema_version':'1','required':[{'module':'predict','render':'structure3d','min_count':1},{'module':'predict','render':'text','min_count':1}]}}
(lab/'lab.yaml').write_text(yaml.safe_dump(manifest,sort_keys=False))
